### ISSUE TITLE
Auth Middleware

### ISSUE THREAD

**Issue by AllKinds** [meateam/api-gateway#6]
Create a middleware that cheks the jwt. If the client didn't sent it, you should redirect to the Authentication Service

**Comment by omrishtam** [comment]
`develop` branch of api-gateway `docker-compose.yml` doesn't work now since the service depends on other services which are not yet configured.

This should've been done in the `feature/auth` branch but now it's in `develop` so anyone using `docker-compose.yml` in branches of `develop` after #15 has been merged should be aware of this issue.

This issue can be closed after adding these services to the `docker-compose.yml` and checking that authentication works...

**Comment by omerzamir** [comment]
solved by #46 and merged to develop.
